version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  db_data: